### ISSUE TITLE
US6 - Service List (UD)

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#11]
## Value proposition

`As a` hotel guest
`I want to` see a list of available services
`In order to` research my options while staying in the hotel

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/503bf646-8ebe-4557-a498-c15b57a4feba)

## Acceptance criteria

- [ ] On the User Dashboard homepage, the user can see the following: 
  - [ ] the name of the hotel: "Hotel Tishjama"
  - [ ] a small text: "Welcome! On this page, you will find a list of Hotel Tishjama's bookable luxury services! Enjoy your stay."
  - [ ] the word "Services"
  - [ ] a list of services, including the name of the service and a placeholder image (real images to be added during styling)
- [ ] In the event of an error, you can see an error message "Our apologies, but we couldn't retrieve the list of our services. Please try again later."
- [ ] At the top of the page, the user can find a link to the Service Provider Dashboard

## Tasks

- [x] create feature branch: feature/service-list-UD

### User Dashboard Creation
- [x] in `pages/index.js` return the function ServiceList

## Simple Dashboard Switching
- [x] in `pages/index.js` add link to `pages/SPD/index.js` and add "Service Provider Dashboard"
- [x] in `pages/SPD/index.js` add link to `pages/index.js`and add "User Dashboard"

## User Dashboard Welcome text
- [x] create a `<p>`element at the top of the page with the text: "Welcome! On this page, you will find a list of Hotel Tishjama's bookable luxury services! Enjoy your stay."

**Comment by ahohnsen** [comment]
Heyho!

Beautiful value proposition 🥳 

I have a few suggestions:

**Scribble**
Will the links for switching between the User Dashboard and the Service Provider Dashboard be labeled as depicted in your sketch? In my view, it would be beneficial not to use abbreviations in this context, as the majority of users may not readily grasp the meanings of "UD" and "SPD." 🤔🤔 

**Acceptance Criteria**
Please keep in mind, that we do not want to use technical terms in the acceptance criteria. Therefore I would suggest the following:


- [ ] On the User Dashboard [UD] homepage, the user can see the following:
    - [ ] the name of the hotel: "Hotel Tishjama"
    - [ ] a small text <strike>`<p>`</strike>: "Welcome! On this page, you will find a list of Hotel Tishjama's bookable luxury     services! Enjoy your stay."
   - [ ] the word "Services"
   - [ ] a list of services, including the name of the service and a placeholder image (real images to be added during styling)
- [ ] In the event of an error, you can see an error message. ☝️**If you do not display the error message in your scribble, please specify here, what the error message will look like (What does the message say?)**
- [ ] At the top of the page, the user can find a link to the SPD ~~(this will be refactored with the addition of a nav bar)~~
