### ISSUE TITLE
US7 - Service Details (UD)

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#12]
## Value proposition

`As a` hotel guest
`I want to` review the details of the hotel's various services
`In order to` better decide which hotel services I might use during my stay

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/290e7da7-4cb9-43d7-bc79-73444ca30a66)

## Acceptance criteria

- [ ] if the user clicks an entry in the service list, the detail entry for that service is shown
- [ ] on the detail page, the user can see the following:
  - [ ] the hotel name, "Hotel Tishjama"
  - [ ] a small text, "Here are the details of the luxury service you selected" 
  - [ ] the word "Service"
  - [ ] a card containing information about the service:
    - [ ] the name of the service
    - [ ] a placeholder image
    - [ ] a description of the service
    - [ ] date and time of the offered service
    - [ ] the price of the offered service
  - [ ] under the card, a button that links back to the User Dashboard
- [ ] in the event of an error, the user will see an error message

## Tasks

- [x] create a branch: `feature/service-details-ud`

### File Structure
- [x] create new folder and file: `/pages/[id].js`

### User Dashboard Service Details Creation
- [x] in `/pages/[id].js` return the function ServiceCard
- [x] create a link from `/pages/[id].js` back to `/pages/index.js`

### User info text
- [x] in `/pages/[id].js` create a `<p>` element in top of the page with the text: "Here are the details of the luxury service you selected" 

```

**Comment by ahohnsen** [comment]
Beautiful! ✨ 

Only one question/suggestion:

It seems like the link to switch between the UD and the SPD has disappeared. 🤔 If I remember correctly, you will implement it in the previous User Story. So the link should be also visible in this scribble.
