### ISSUE TITLE
US8 - Book Service (UD)

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#14]
## Value proposition

`As a` hotel guest
`I want to` book a service of my choosing, see all my booked services in one place, see the details of each booked service, and cancel bookings
`In order to` have an overview of my activities/appointments during my stay and enjoy my stay more thoroughly

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/15c7ec7c-0978-495a-88df-cd98d58fa8b0)

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/80f5cea2-c7c4-443e-a316-e2dc135b2ac1)

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/5fcc44c0-851e-492d-beda-483115ee614d)

### Part 1
- [ ] on any/every service details page, the user will see a button which says "Book This Service"
  - [ ] clicking this button will:
    - [ ] ~~make the button inactive and~~ change the text of the button to "Cancel Booking"
    - [ ] add a "← My Bookings" link at the bottom of the page
    - [ ] ~~set a ★ icon on~~
      - [ ] ~~the service details page of the booked service~~
      - [ ] ~~the booked service's entry on the service list~~

- [ ] on top of the Service List, the user can see a button with the text " ~~★~~ My Bookings"
- [ ] when the user clicks this button, they are taken to a new page
  - [ ] if the user has not yet booked any services, the page shows " ~~★~~ My Bookings" and the following message: "You have not yet booked any of our luxury services. To make a booking, please go to Services."
  - [ ] on this error page, the user will also see a "← Services" button which returns the user to the User Dashboard
- [ ] if the user _has_ booked services, they will see 
  - [ ] the words " ~~★~~ My Bookings" and a list of services they have booked
    - [ ] each item in the list on the " ~~★~~ My Bookings" page shows the following:
      - [ ] placeholder image for the booked service
      - [ ] name of the booked service
      - [ ] date and time of the booked service
      - [ ] ~~a ★ icon~~
  - [ ] a "← Services" button which returns the user to the User Dashboard

### Part 2
- [ ] the appointment details page looks essentially like the service details page, and contains the following elements
  - [ ] service name
  - [ ] service (placeholder) image
  - [ ] description of service
  - [ ] date (which is now set)
  - [ ] time (which is now set)
  - [ ] price with currency
  - [ ] a link back to the booked services list which contains the text "˿ My Bookings"
- [ ] in the event of an error, you can see an error message: "Our apologies, but we couldn't retrieve that particular service. Please try again later."

### Part 3
- [ ] on the Booking Details page, there should be a "Cancel Booking" button
- [ ] if the user clicks the "Cancel Booking" button, a confirmation message appears
  - [ ] this confirmation message contains the following:
    - [ ] the text: "Are you sure you want to cancel this booking?"
    - [ ] ~~a "No" button, which returns the user to the Booking Details page~~
    - [ ] ~~a "Yes" button, which cancels the booking, and returns the user to the My Bookings page, where the booked service no longer appears~~ 

## Tasks
- [x] create branch: `feature/book-service`

### Remodel Data Model
- [ ] ~~add boolean "is booked" to the data structure both in MongoDB and the schema in `/db/models/service.js`~~

### Adjust File Tree
- [x] create `/pages/MyBookings/index.js`

### New Component
- [x] create `/components/MyBookings/index.js`
- [x] use the code from `/components/ServiceList/index.js` and refactor the following:
  - [x] component name
  - [x] 1st error: delete
  - [x] 2nd error: "You have not yet booked . . ." and move it to after the array method
    - [x] add a link with the text "← Services" to this error page
  - [x] change the array method to `filter` to render a list of services where the boolean "isBooked" is set to "true"

### Create "Book This Service" Button
- [x] create `/components/IsBooked/index.js`
  - [ ] ~~and write a "favoriting" function~~
    - [ ] ~~which makes use of useState with the props "isBooked," and "setIsBooked" and the initial value of "false"~~
    - [x] and that returns a button on each details page in the User Dashboard
      - [x] which has an onClick function 
      - [x] and a ternary operator that
        - [x] changes the text from "Book This Service" to "Cancel Service ~~Booked~~ "
        - [ ] ~~makes the button (for now) inactive~~

### Render My Bookings page
- [x] in `/pages/MyBookings/index.js` render the component `MyBookings`
- [ ] ~~render list in chronological order using a sort method~~ [has been added to `USX - Refactoring`]
- [x] create link/back button and
  - [ ] ~~add ternary operator so that, when a service is booked:~~
    - [ ] ~~the button's text changes from "← Services" to "← ~~★~~ My Bookings"~~
    - [ ] ~~the button's link changes from leading to the service list page to leading to the ~~★~~ My Bookings page~~

### Set Link from User Dashboard Service List
- [x] in `/pages/index.js` create a link with the text "~~★~~ My Bookings" 

- [x] create `pages/MyBookings/[id].js` and
  - [x] reuse the component `ServiceCard`
  - [x] create a link back to the `MyBookings` page

- [x] on the Booking Details page, under the card, render a "Cancel Booking" button
  - [x] use the DELETE method here
- [x] create confirmation message

**Comment by ahohnsen** [comment]
Hi!

Again, very well written 🙂 

As discussed, I suggest to merge this user story with the next one. 👍🏼

**Comment by miriam-ertl** [comment]
Very good job 😀.
I clearly understood the AC you wrote and the connected tasks.
there is just one small suggestion I would have, instead of 
- [ ] toward the top of the Service List, the user can see a button with the text "★ My Bookings" 

better to understand for me would be :
- [ ] On top of the Service List, the user can see a button with the text "★ My Bookings"
