### ISSUE TITLE
US9 - Display Booked Services (UD)

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#15]
## Value proposition

`As a` hotel guest
`I want to` see all my booked services in one place
`In order to` have an overview of my activities/appointments during my stay

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/31847f8c-92d3-46eb-b004-87a36a335a0d)

## Acceptance criteria

- [ ] toward the top of the Service List, the user can see a button with the text "★ my bookings"
- [ ] when the user clicks this button, they are taken to a new page
  - [ ] if the user has not yet booked any services, the page shows "★ My Bookings" and the following message: "Sorry, you have not yet booked any of our luxury services. To make a booking, please go back."
  - [ ] on this error page, the user will also see a "← back" button which returns the user to the User Dashboard
- [ ] if the user _has_ booked services, they will see 
  - [ ] the words "★ My Bookings" and a list of services they have booked
    - [ ] each item in the list on the "★ my bookings" page shows the following:
      - [ ] placeholder image for the booked service
      - [ ] name of the booked service
      - [ ] date and time of the booked service
  - [ ] a "← back" button which returns the user to the User Dashboard

## Tasks
- [ ] create a branch: feature/my-bookings

### Adjust File Tree
- [ ] create `/pages/UserDashboard/MyBookings/index.js`

### New Component
- [ ] create `/components/MyBookings/index.js`
- [ ] use the code from `/components/ServiceList/index.js` and refactor the following:
  - [ ] component name
  - [ ] 1st error: delete
  - [ ] 2nd error: "Sorry, you have not yet booked . . ." and move it to after the array method
    - [ ] add a link with the text "← back" to this error page
  - [ ] change the array method to `filter` to render a list of services where the boolean "isBooked" is set to "true"

### Render
- [ ] in `/pages/UserDashboard/MyBookings/index.js` render the component `MyBookings`
- [ ] create a link with the text "← back" which links back to the User Dashboard

### Set Link from User Dashboard Service List
- [ ] in `/pages/UserDashboard/index.js` create a link with the text "★ My Bookings"

**Comment by JessicaLoers** [comment]
**Hey Tishjama** 
as mentioned this morning, please connect the User Story **Book a Service 8** and **Display a Service 9**.
Afterwards you can post the user story again. 💚
