### ISSUE TITLE
US9 - Styling: Architecture

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#19]
## Value proposition

`As a` hotel service manager & hotel guest
`I want to` have an app that both looks good and is accessible
`In order to` more easily use the app to provide services to the hotel's customers & more easily use the app to find and book services provided by the hotel

## Description

- This is the basic architectural design of our app. To describe each and every element in detail would take too much of our time and yours. Please use the following as a guide and not as written in stone.

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/28b25b25-bc29-4914-a6f1-ceff0dafb52e)

## Acceptance criteria

- the "styling architecture" of each page will have a uniform and standardized look and feel
  - this will include the look, behavior, and positioning of the following:
  - [ ] `<link>`/`<button>` 
  - [ ] `<ul>` 
  - [ ] `<li>` 
  - [ ] `<image>` 
  - [ ] `<article>`
  - [ ] `<paragraph>`
  - [ ] `<form>`
  - [ ] `<h2>` `<h3>`

## Tasks

- [x] create branch: feature/styling-architecture
- [x] import styled
- [x] create `components/Layout/`
- [x] create styled component & set tags for the following:
  - [x] `<link>`
  - [x] `<link>` styled as `<button>` 
  - [x] `<ul>` 
  - [x] `<li>` 
  - [x] `<image>` 
  - [x] `<article>`
  - [x] `<paragraph>`
  - [x] `<form>`
  - [x] `<h2>` `<h3>`

**Comment by TobiasSteinhagen** [comment]
Hello there,

we observed just some small things regarding the scribbles 🙂

1. Where is the scribble of the form page (where the hotel manager can add the services, if that is what you meant)?
2. I can see buttons on your scribbles, but I think that are links (styled as a button), where are buttons like "book" or "cancel"? 

Overall, great US ✌️

P.S. Just a little suggestion, your h3 (I guess) under your h1, do you really need these? I think the page makes it clear, what the user sees and it is really small and overloads the header of the page a little bit.🦑

**Comment by TobiasSteinhagen** [comment]
Looks great, just a tiny suggestion.
You have two pages:

- user dashboard
- service provider dashboard

For that, you have two links (which are styled the same way 👍), but they are in different positions because of the `<Paragraph>` on the user dashboard page.

Maybe it would be a nice adjustment (for the look and feel of the app, and the standardized layout), to move the `<Paragraph>` under the link, or to forego it?

Overall, great work ✌️🚀

**Comment by shrocket** [comment]
Thank you for your comments! We kind of made the changes you suggested: The dashboard switching button should have been under the `<h2>` and the whole time. But we didn't change it maybe as much as you would have liked for two reasons: 
1. no user is ever going to be switching back and forth often enough to be horribly bothered by the positioning discrepancy
2. those switching buttons will disappear as soon as a user login is implemented
