### ISSUE TITLE
US1 - Service List (SPD)

### ISSUE THREAD

**Issue by ohlunlacassi** [ohlunlacassi/hotel-tishjama#2]
## Value proposition

As a Hotel Service Manager
I want to see a list of our services
In order to have an overview of all services currently provided by the hotel

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139952562/5c6cd6c9-458e-4898-a749-7bae59c842d0)

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139952562/008d0438-6d45-4fad-96d2-d8723d0a18d8)

## Acceptance criteria

- [ ] On the homepage, you can see the following:
    - [ ] the name of the hotel: "Hotel Tishjama"
    - [ ] the word "Services"
    - [ ] a list of services, including the name of the service and a placeholder image (real images come during styling)
- [ ] In the event of an error, you can see an error message.

## Tasks

- [x] create feature branch: feature/service-list
- [x] on mongo.db, create a database called "Tishjama" and a collection called "services
  - [x] enter the preexisting list of services into the collection
- [x] fetch a list of services from the API
  - [x] implement the error handling logic to display an error message if there is an issue loading data from the API
- [x] map through the fetched list of services

- [x] in _app.js:
  - [x] render an `<h1>` element for the hotel/app name

- [x] in the index.js:
  - [x] render an `<h2>` element for the word "Services"
  - [x] render an unordered list which contains all services and shows for each service: 
    - [x] the name of the service
    - [x] an image
    

```
