### ISSUE TITLE
US10 - Booking Details (UD)

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#20]
## Value proposition

`As a` hotel guest
`I want to` see the details of my booked appointments
`In order to` better plan and enjoy my stay in Hotel Tishjama

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/812e4713-0543-4e98-b67f-4059e4bab2c6)

## Acceptance criteria

- [ ] the appointment details page looks essentially like the service details page, and contains the following elements
  - [ ] service name
  - [ ] service (placeholder) image
  - [ ] description of service
  - [ ] date (which is now set)
  - [ ] time (which is now set)
  - [ ] price with currency
  - [ ] a link back to the booked services list which contains the text "˿ My Bookings"
- [ ] in the event of an error, you can see an error message: "Our apologies, but we couldn't retrieve that particular service. Please try again later."

## Tasks

- [x] create a feature branch: `feature/booking-details`
- [x] create `pages/MyBookings/[id].js` and
  - [x] reuse the component `ServiceCard`
  - [x] create a link back to the `MyBookings` page

**Comment by miriam-ertl** [comment]
Your User Story is very good to understand and clearly formulated, especially the value proposition and the ac.  👍🏻👍🏻👍🏻
 It might help to highlight the functional words like `feature/booking-details` and `pages/MyBookings/[id].js` and `ServiceCard` in the tasks the same way. But this is just a stylistic remark.
