### ISSUE TITLE
US11 - Cancel Booking

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#21]
## Value proposition

`As a` hotel guest
`I want to` cancel a booking
`In order to` control the schedule of my stay more easily

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/76da75be-d74d-4997-8d77-01ee2037b1c4)

## Acceptance criteria

- [ ] on the Booking Details page, there should be a "Cancel Booking" button
- [ ] if the user clicks the "Cancel Booking" button, a confirmation message appears
  - [ ] this confirmation message contains the following:
    - [ ] the text: "Are you sure you want to cancel this booking?"
    - [ ] a "No" button, which returns the user to the Booking Details page
    - [ ] a "Yes" button, which cancels the booking, and returns the user to the My Bookings page, where the booked service no longer appears 

## Tasks

- [ ] create branch: `feature/cancel-booking`
- [ ] on the Booking Details page, under the card, render a "Cancel Booking" button
  - [ ] use the DELETE method here
  - [ ] call the component CancelBooking
- [ ] create confirmation message

**Comment by AnnaD91** [comment]
A big part of your user story is about the confirm message when canceling an existing booking. Unfortunately, it does not appear in your scribble. 

Also, we would recommend to extend the tasks i.e. regarding the confirmation messages: "Where do you want to render the confirmation messages?", "What would be the name of the component?", etc. Same applies for the cancel button: "Where do you want to apply the DELETE-method?" It would help if you would go more into details here 😊
