### ISSUE TITLE
US10 - Styling: Aesthetics

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#22]
## Value proposition

`As a` hotel service manager & hotel guest
`I want to` have an app that both looks good and is accessible
`In order to` more easily use the app to provide services to the hotel's customers & more easily use the app to find and book services provided by the hotel

## Description

- This is the basic aesthetic design of our app, which mostly deals with colors. To describe each and every element in detail would take too much of our time and yours. Please use the following as a guide, and not as written in stone.

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/300a339b-c64e-4d7f-98b8-1eff55271905)

## Acceptance criteria

- the "styling aesthetics" of each page will have a uniform and standardized look and feel
  - this will include the look, behavior, and positioning of the following:
 - [ ] color theme for the entire site
 - [ ] font family
 - [ ] **Please Note**: the stars were removed in US8!

## Tasks

- [x] create branch: feature/styling-aesthetics
- [x] create/edit styled component & set tags for things like
  - [x] the header
  - [x] the various heading levels (`<h1>` `<h2>` `<h3>` . . . )
    - [x] in styling components, make H2 "StyledHeadlineTwo"

**Comment by AnnaD91** [comment]
Looks good 🚀 Just a small recommendation: There should be no technical terms in the acceptance criteria (like in your case `<h1>, <h2>, <h3>,` color theme etc.) Instead this should appear in the task section.

Header and heading are two different elements, it is not obvious what exactly you mean by that? 😊
