### ISSUE TITLE
US11 - Login Page

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#25]
## Value proposition

`As a` Service Manager _or_ a Hotel Guest
`I want to` log into the app
`In order to` manage our services/my bookings

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/a59d03a7-8e57-4ba0-8cbf-a7bb065710a0)

## Acceptance criteria

- [ ] on the `homepage` there is a small text which reads, "To use our services, please log in."
- [ ] behind that is a link called "login" which, when clicked, leads the user to a login page
- [ ] on the login page, there is a form which shows the following:
  - [ ]  a username/email address field
  - [ ] a password field
  - [ ] a submit button
- [ ] when a Guest logs in, they are redirected to the homepage (now the User Dashboard [UD]), where they now see, instead of the login text, the following:
  - [ ] Welcome, `<first name>` `<last name>`!
  - [ ] a logout link
  - [ ] a link "My Bookings"
- [ ] when a Service Manager logs in, they are redirected to the Service Provider Dashboard [SPD], where there is now also a logout link
  - [ ] and the "Book this Service" button on the Service Details Page disappears
- [ ] if a User enters incorrect login data, they see a warning message 

## Tasks

- [ ] create a branch `feature/login-page`
- [ ] update data schema with new User data
- [ ] refactor dashboard switching links
- [ ] create `login div` on homepage
- [ ] write a component `LoginForm`
  - [ ] include form and error handling
- [ ] write a component LogIn
- [ ] write a component LogOut
- [ ] write page `/pages/login.js`
- [ ] use router/pathname thingy to remove the "Book this Service" from the SPD Service Details Page/s

**Comment by miriam-ertl** [comment]
Excellent★★★★★
