### ISSUE TITLE
US12 - Add Photos (w/Cloudinary)

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#27]
## Value proposition

`As a` Hotel Guest or Service Manager
`I want to` see a pretty eyecatcher in the form of a photo
`In order to` produce anticipation in the viewer

## Description

- in the places where the wireframes show boxes with Xs through them, there are now descriptive photos of the offered services

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139855611/647a848c-fc19-435f-84ef-3db2b9d3b0bc)

## Acceptance criteria

- [ ] in the places where the wireframes show boxes with Xs through them, there are now descriptive photos of the offered services

## Tasks

- [ ] create branch `feature/add-photos`
- [ ] implement an image platform such like Cloudinary, to upload, store and display images (with the gained knowlegde of the session on Monday)

**Comment by miriam-ertl** [comment]
It was cool reading your User Story. And I get a picture what you want to work on in this user story.
I just have minor suggestions to the VP and one task.

### VP
**As a** Hotel Guest or Service Manager 
**I want to** see a pretty eyecatcher 
**In order to** convince me of the offered service and triggering prefeuds (Vorfreude)

### Tasks

- Implement an image platform such like Cloudinary, to upload, store and display images (with the gained knowlegde of the session on Monday)
