### ISSUE TITLE
US13 - Refactoring

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#28]
## Value proposition

`As a` developer
`I want to` have clean code
`In order to` provide a smoother and faster user experience

## Description

- this is an invisible user story

## Acceptance criteria

- [ ] Clean(er) code
  - [x] "book service" button no longer visible when no one is logged in
  - [x] "book service" button no longer visible in SPD
  - [ ] no unnecessary lines (e.g. remove all console.logs)
  - [ ] e.g. customize fetcher to throw specific errors.
  - [ ] react styling components with props?

## Tasks

- [ ] go through each page of code with a fine-toothed comb and look for places ripe for optimization
