### ISSUE TITLE
US2 - Details of a Service (SPD)

### ISSUE THREAD

**Issue by TienPham18** [ohlunlacassi/hotel-tishjama#3]
## Value proposition

As a... hotel service manager
I want to... review the details of the services
In order to.. better know exactly what services the hotel is offering its guests

## Description

![Image](https://user-images.githubusercontent.com/52444935/268292148-222a53a1-8366-4979-b915-f1885f6552c5.png)

## Acceptance criteria

- [ ] if you click an entry in the service list, the detail page for that service is shown
- [ ] on the detail page,  you can see the following:
  - [ ] the hotel name, "Hotel Tishjama"
  - [ ] the word "Service"
  - [ ] a card containing the information about the service: 
    - [ ] the name of the service 
    - [ ] a placeholder image (real images will be placed during styling) 
    - [ ] a description of the service 
    - [ ] date and time of the offered service
    - [ ] the price of the offered service
  - [ ] under the card, a button that links back to the homepage
- [ ] in the event of an error, you can see an error message  

## Tasks

- [x] create a feature branch: feature/detail-page
- [x] create "components/ServiceCard/index.js"  
  - [x] in the return statement render the following: 
    - [x] an `<h2>` element "Service"
    - [x] an `<article>` which contains the following information:
      - [x] service placeholder image
      - [x] service name
      - [x] description
      - [x] date
      - [x] time
      - [x] price with currency (€)
    - [x] a link back to the service list page which contains the text "<- back"

- [x] create "pages/api/services/[id].js"
  - [x] fetch one service by id
- [x] create "pages/[id].js
  - [x] render services individually

- [x] create a link from service list items to the "ServiceCard" by id

```

**Comment by JessicaLoers** [comment]
**Well done Team Tishjama 🏨**
You can complete the tasks on Monday.
