### ISSUE TITLE
US14 - Styling Updates

### ISSUE THREAD

**Issue by ohlunlacassi** [ohlunlacassi/hotel-tishjama#30]
## Value proposition

`As a` hotel service manager and hotel guests
`I want to` have an app that both looks good and is accessible
`In order to` more easily use the app to provide the services to hotel guests and more easily use the app to find and book hotel services

## Description

- [ ] colors, fonts, spacing, shapes all appear as they did in [US10](https://github.com/ohlunlacassi/hotel-tishjama/issues/22)

## Acceptance criteria

- [ ] the styling of each page will have a uniform and standardized look and feel
- [ ] of particular interest are the login bar and page

## Tasks

- [ ] create branch: feature/styling-updates
- [ ] add styling to login bar and page

**Comment by miriam-ertl** [comment]
Thank you for sharing your US. Looking forward to your styling. Everything is written clearly and excellent.★★★★★
