### ISSUE TITLE
US3 - Add a Service (SPD)

### ISSUE THREAD

**Issue by ohlunlacassi** [ohlunlacassi/hotel-tishjama#4]
## Value proposition

As a hotel service manager
I want to add a service
In order to offer our guests even more services

## Description

![Image](https://user-images.githubusercontent.com/139991612/268308734-142d90ec-3ed4-4f63-bc57-c12390099b84.png)

## Acceptance criteria

- [ ] on the service list, there is a button to add a new service
- [ ] when the "Add Service" button is clicked, the user should be directed to a new page with a form to add the service details
- [ ] on the form page, the user can see the following:
  - [ ] the hotel name "Hotel Tishjama"
  - [ ] the words "Add service"
  - [ ] a form which contains the fields:
    - [ ] a text field: "service name"
    - [ ] a text field: "image"
    - [ ] a text area: "description"
    - [ ] a date picker: "date" 
    - [ ] a time picker: "time"
    - [ ] a number field with currency (€): "price"
    - [ ] a "cancel" button which directs the user back to the service list page
    - [ ] an "add service" button--if the form is successfully submitted, the user should be directed back to the service list page where the new service is displayed

      - [ ] if the user tries to submit an empty form, an error message is displayed indicating which fields are mandatory (all fields are mandatory)

## Tasks

- [x] create a branch: feature/add-service
- [x] create "components/ServiceForm/index.js"
- [x] create an `<h2>` element: "Add Service"
- [x] create a form with the following fields:
  - [x] service name
  - [x] image 
  - [x] description
  - [x] date
  - [x] time
  - [x] price
    - [x] (all fields are required) 
  - [x] create a "cancel" button that links back to the service list page without saving 
  - [x] create an "add" button 

```

**Comment by JessicaLoers** [comment]
Good work. ✨
Here are some suggestions to improve this User Story. 

- if you click that button, a form opens.
➡️ _Please specify. The form does not open, but the user is redirected to a new page_
**Example:** 
Upon clicking the "Add New Service" button, you should be navigated to a new page with a form to add the service details.

-  a form which contains the fields which can receive text:
➡️ _These input fields can/should not be a text field._
- Date (Date picker)
- Time (Time picker)
- Price (Numeric field with currency)

- "add service" button which links back to the service list page, where the new service is displayed
➡️  _Please specify_
**Example:** 
If the form is **successfully submitted**, the user should be navigated back to the service list page where the new service is displayed.

➡️  _The user story doesn't mention what happens if the form isn't filled out correctly or if there are errors during submission. It would be beneficial to add criteria about form validation and error messages._

**Example**
- If the user tries to submit an empty form, an error message is displayed indicating which fields are mandatory.
- All form fields must be labeled clearly.

➡️ _Consider adding a confirmation prompt after the "add service" button is clicked. This ensures that the user confident in the information they’ve provided before it’s added to the service list._

**Example**
- The user receives a confirmation prompt or message when the form is successfully submitted.

**Comment by shrocket** [comment]
Thank you for this feedback! And LOL: We talked about your final point ("➡️ Consider adding a confirmation prompt after the "add service" button is clicked. This ensures that the user confident in the information they’ve provided before it’s added to the service list.") for a long time, and came to the conclusion that, since we had never, in any of the CRUD examples we'd been shown, seen such a confirmation prompt, we probably didn't need to include one. 😄
