### ISSUE TITLE
US4 - Delete a Service (SPD)

### ISSUE THREAD

**Issue by shrocket** [ohlunlacassi/hotel-tishjama#5]
## Value proposition

As a hotel service manager
I want to delete a service
In order to keep the list of available services up to date

## Description

![Image](https://github.com/ohlunlacassi/hotel-tishjama/assets/139952562/46491e5b-ca97-4688-b7a8-230997b20410)

## Acceptance criteria

- [ ] on the service details page, there is a "delete" button
  - [ ] the "delete" button ~~has a red background and~~ contains a delete icon (❌) as well as the word "delete"
- [ ] if the user clicks the "delete" button, a deletion confirmation message appears
  - [ ] this confirmation message contains the following:
    - [ ] the text "Are you sure you want to delete this service?"
    - [ ] a "cancel" button, which, when clicked, causes the confirmation message to disappear, bringing the user back to the service details page
    - [ ] an "OK" button, which, when clicked, directs the user back to the service list page, where the deleted service no longer appears
  - [ ] if the user deletes all services, the service list page shows the message "There are currently no services available. Please add a service"

## Tasks

- [x] create a branch: feature/delete-service
- [x] on the service details page, under the card create a " X delete" button
- [x] create confirmation message that appears when the button is clicked, and which has:
  - [x]  the text: "Are you sure you want to delete this service?"
  - [x] a ~~red~~ button with the text "❌ delete"
  - [x] a button with the text "cancel" 
- [x] if all services are deleted, render the following text, "There are currently no services available. Please add a service" on the service list page
 

```

**Comment by JessicaLoers** [comment]
**Nice Story 👏** 

But of course I have one small and mean comment. 😈
- _What happens when the users delete all existing entries?_
- _What do the users see on the service list page?_

Please do not forget to complete the tasks.
